-- Reset download_history table
drop table if exists download_history;

create table download_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.usuarios(id),
  start_date date not null,
  end_date date not null,
  total_files int default 0,
  zip_name text,
  zip_path text,
  status text check (status in ('pending', 'processing', 'ready', 'error')) default 'pending',
  error_message text,
  created_at timestamptz default now()
);

alter table download_history enable row level security;

-- Policy for download_history (API uses Service Role, but good to have)
-- Drop if exists to be safe, though table drop handles it usually
drop policy if exists "Enable access to all users" on download_history;

create policy "Enable access to all users"
on download_history for all
using (true)
with check (true);

-- Storage Setup
-- 1. Create bucket if not exists
insert into storage.buckets (id, name, public)
values ('downloads', 'downloads', true)
on conflict (id) do nothing;

-- 2. Safely recreate policies (Drop first to avoid 42710 error)
drop policy if exists "Authenticated users can upload downloads" on storage.objects;
drop policy if exists "Authenticated users can read downloads" on storage.objects;

create policy "Authenticated users can upload downloads"
  on storage.objects for insert
  with check (bucket_id = 'downloads');

create policy "Authenticated users can read downloads"
  on storage.objects for select
  using (bucket_id = 'downloads');
